port: "8080"

postgres:
  url: "postgres://vyacheslav:1234@127.0.0.1:5432/trading_sim?sslmode=disable"
redis:
  url: "localhost:6379"
  password: ""
  db: "1"

currencies: "btcusdt,ethusdt,bnbusdt,solusdt,adausdt,xrpusdt,dotusdt,dogeusdt,shibusdt,lunausdt,avaxusdt,ltcusdt,linkusdt,ftmusdt,uniusdt,bchusdt,hbarusdt,algousdt,maticusdt,vetusdt,xlmusdt,trxusdt,axsusdt,icpusdt,filusdt,atomusdt,etcusdt,thetausdt,nearusdt"
