port: "8080"

db:
  url: "postgres://postgres:postgres_pass@pg:5432/tbot?sslmode=disable"

currencies: "btcusdt,ethusdt,bnbusdt,solusdt,adausdt,xrpusdt,dotusdt,dogeusdt,shibusdt,lunausdt,avaxusdt,ltcusdt,linkusdt,ftmusdt,uniusdt,bchusdt,hbarusdt,algousdt,maticusdt,vetusdt,xlmusdt,trxusdt,axsusdt,icpusdt,filusdt,atomusdt,etcusdt,thetausdt,nearusdt,fttusdt"