port: "8080"

postgres:
  username: ""
  password: ""
  host:     "localhost"
  port:     "5432"
  dbName:   "trading_sim"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "1"

currencies: "btcusdt,ethusdt,bnbusdt,solusdt,adausdt,xrpusdt,dotusdt,dogeusdt,shibusdt,lunausdt,avaxusdt,ltcusdt,linkusdt,ftmusdt,uniusdt,bchusdt,hbarusdt,algousdt,maticusdt,vetusdt,xlmusdt,trxusdt,axsusdt,icpusdt,filusdt,atomusdt,etcusdt,thetausdt,nearusdt"
